version: '3.8'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: egu4EPE.jkt5dzw6hpe
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: CXT3fpq*zhb6ejk@cfe
    networks:
      - wordpress_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  wordpress:
    image: wordpress:latest
    ports:
      - "8086:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: CXT3fpq*zhb6ejk@cfe
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - /mnt/swarm-data/Projects/github-actions-pod/wp-btechit/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wordpress_net
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  wordpress_net:
    driver: overlay

volumes:
  db_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.2.42,rw,vers=3
      device: ":/swarm01-data/service/mysql-btechit/"
  wordpress_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.2.42,rw,vers=3
      device: ":/swarm01-data/service/wp-btechit/"
