version: '3.13'
services:
  agent:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=n8n
      - N8N_BASIC_AUTH_PASSWORD_FILE=/run/secrets/n8n_password
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD_FILE=/run/secrets/postgres-n8n_password
      - NODE_FUNCTION_ALLOW_EXTERNAL=axios,qs
      - N8N_SECURE_COOKIE=false
      - N8N_EDITOR_BASE_URL=http://192.168.2.11:5678
      - WEBHOOK_URL=http://192.168.2.11:5678

    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - /mnt/swarm-data/service/n8n:/home/node/.n8n
    secrets:
      - n8n_password
      - postgres-n8n_password
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-n8n_password
      - POSTGRES_DB=n8n
    volumes:
      - /mnt/swarm-data/service/postgres-n8n:/var/lib/postgresql/data
    restart: unless-stopped
    secrets:
      - postgres-n8n_password

secrets:
  n8n_password:
    external: true
  postgres-n8n_password:
    external: true
