version: '3.13'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "81:81"
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/swarm-data/service/nginx/manager-data:/data
      - /mnt/swarm-data/service/nginx/manager-letsencrypt:/etc/letsencrypt
    deploy:
      placement:
        constraints:
          - node.role == manager
