version: '3.13'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/swarm-data/service/nginx/logs:/var/log/nginx
      - /mnt/swarm-data/service/nginx/ssl:/etc/ssl
      - /mnt/swarm-data/service/nginx/sites-enabled:/etc/site-enabled
    deploy:
      placement:
        constraints:
          - node.role == manager

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "81:81"    # Admin UI
      - "8080:80"  # Optional: HTTP (change host port if 80 is in use)
      - "8443:443" # Optional: HTTPS (change host port if 443 is in use)
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
    deploy:
      placement:
        constraints:
          - node.role == manager
