version: '3.13'

services:
  proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy-manager
    restart: unless-stopped
    ports:
      - "81:81"
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/swarm-data/service/nginx/manager-data:/data
      - /mnt/swarm-data/service/nginx/manager-letsencrypt:/etc/letsencrypt
      - /mnt/swarm-data/service/nginx/logs:/var/log/nginx
    deploy:
      placement:
        constraints:
          - node.role == manager
