version: '3'
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "27017:27017"

volumes:
  mongo:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.2.42,rw,vers=3
      device: ":/swarm01-data/service/mongo-margin/"
