version: '3.8'

services:
  agent:
    image: portainer/agent:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host
    environment:
      CAP_HOST_MANAGEMENT: "1"
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [ node.platform.os == linux ]

  portainer:
    image: portainer/portainer-ee:lts
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
#      - "9443:9443" # HTTPS access
      - "9000:9000" # HTTP access (nginx will handle SSL)
#      - "8000:8000" # for Edge agents
    volumes:
      - /mnt/swarm-data/service/portainer:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

networks:
  agent_network:
    driver: overlay
    attachable: true
